name: Rexfords
favicon: null
layout_spectrum: 0.24492
typography_spectrum: 0.26866
title: Healthy Meal Preparation and Delivery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fdcd00'
    - '#003400'
    - '#f23b00'
    - '#83a500'
  brandStrength: 0.600694224534996
  lightness: 0.033701029784501624
  saturation: 0.29437921506503173
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
