name: Rexfords
favicon: null
layout_spectrum: 0.9058391767637309
typography_spectrum: 0.292353280060511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#eb0000'
    - '#feb400'
    - '#010602'
    - '#009500'
  brandStrength: 0.600694224534996
  lightness: 0.033701029784501624
  saturation: 0.29437921506503173
  rhythmicContrast: 0.42300674811119066
purpose:
  - name: null
    item: null
    url: null
